confirm_os_window_close 0
#background_blur 1
background_opacity 0.90
hide_window_decoration yes

font_family Fira Code
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0

tab_bar_edge top
tab_bar_style fade
tab_fade 0.25 0.5 0.75 1

# BEGIN_KITTY_THEME
# rose-pine moon
include theme.conf
# END_KITTY_THEME
